export { default as DashboardImage } from './images/dashboard-view.png'
export { default as DesignWizardBadge1Image } from './images/design-wizard-badge1.png'
export { default as DesignWizardBadge2Image } from './images/design-wizard-badge2.png'
export { default as GithubProfileViewImage } from './images/github-profile.png'
export { default as SignImage } from './images/sign.png'
