export { ArrowDownIcon } from './ArrowDownIcon'
export { ArrowTrendingUpIcon } from './ArrowTrendingUpIcon'
export { BoltIcon } from './BoltIcon'
export { BriefCaseIcon } from './BriefCaseIcon'
export { ClipBoardIcon } from './ClipBoardIcon'
export { CommentIcon } from './CommentIcon'
export { CubeIcon } from './CubeIcon'
export { HandRaisedIcon } from './HandRaisedIcon'
export { HeroIcon } from './HeroIcon'
export { HomeIcon } from './HomeIcon'
export { InboxIcon } from './InboxIcon'
export { IterateIcon } from './IterateIcon'
export { LifeBuoyIcon } from './LifeBuoyIcon'
export { LocationIcon } from './LocationIcon'
export { ThumbsUpIcon } from './ThumbsUpIcon'

export { ReactComponent as AcademicCapIcon } from '../../assets/svg/academic-cap.svg'
export { ReactComponent as AndroidIcon } from '../../assets/svg/android.svg'
export { ReactComponent as ClockIcon } from '../../assets/svg/clock.svg'
export { ReactComponent as CrownIcon } from '../../assets/svg/crown.svg'
export { ReactComponent as FlutterIcon } from '../../assets/svg/flutter.svg'
export { ReactComponent as GithubIcon } from '../../assets/svg/github.svg'
export { ReactComponent as InfoIcon } from '../../assets/svg/info.svg'
export { ReactComponent as JavascriptIcon } from '../../assets/svg/javascript.svg'
export { ReactComponent as LinkedInIcon } from '../../assets/svg/linkedin.svg'
export { ReactComponent as Logo } from '../../assets/svg/logo.svg'
export { ReactComponent as MicrosoftIcon } from '../../assets/svg/microsoft.svg'
export { ReactComponent as PHPIcon } from '../../assets/svg/php.svg'
export { ReactComponent as PythonIcon } from '../../assets/svg/python.svg'
export { ReactComponent as RubyIcon } from '../../assets/svg/ruby.svg'
export { ReactComponent as TrophyIcon } from '../../assets/svg/trophy.svg'
export { ReactComponent as ViewerStatsIcon } from '../../assets/svg/viewer-stats.svg'
